mirrors:
  - url: "https://docker.1ms.run"
  - url: "https://docker.1panel.live"
  - url: "https://docker.367231.xyz"
  - url: "https://docker.amingg.com"
  - url: "https://docker.m.daocloud.io"
  - url: "https://docker.m.ixdev.cn"
  - url: "https://dockerproxy.net"
  - url: "https://hub.1panel.dev"
  - url: "https://image.cloudlayer.icu"
